version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql  
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: answering_machine
    restart: always
    env_file:
      - path: ./.env
    depends_on:
      - db

volumes:
  mysql-data: